Add variable to trace unit test
Signed-off-by: Alexey Gladkov <legion@altlinux.org>

diff --git a/shell-unittest b/shell-unittest
--- a/shell-unittest
+++ b/shell-unittest
@@ -243,6 +243,14 @@ runUnitTests()
 		done
 		return 1
 	}
+	run_test()
+	{
+		if [ -n "${TESTTRACE-}" ]; then
+			printf '\n' >&2
+			set -x
+		fi
+		"$1"
+	}
 	run_or_exit()
 	{
 		"$@" || fatal "$1() fail rc=$?"
@@ -265,12 +273,23 @@ runUnitTests()
 		run_or_exit setUp
 
 		rc=0
-		msg="$("$1")" || rc=$?
+		msg="$(run_test "$1")" || rc=$?
 
 		case "$rc" in
 			0) passed=$(($passed+1)) ;;
 			1) failed=$(($failed+1)); retval=1; ;;
 			2) skipped=$(($skipped+1)) ;;
+			*)
+				{
+					printf '\n'
+					printf 'FATAL: Unexpected return code.\n'
+					printf '\n'
+					printf '%s\n' "Testcase '$1' ended with an unexpected return code: rc=$rc"
+					printf '%s\n' "Check its correctness. Return code must be success=0, fail=1, skipped=2."
+				} >&2
+				retval=1
+				break
+				;;
 		esac
 		run_or_exit messageTest "$1" "$msg" "$rc"
 		run_or_exit tearDown
