github: Add DSO check
Signed-off-by: Alexey Gladkov <legion@altlinux.org>

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -25,6 +25,31 @@ jobs:
       - name: "make docs"
         run: make man
 
+  check-commits:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: "Developer's Certificate of Origin"
+        run: |
+          echo
+          echo 'Commits to check:'
+          echo '${{ toJSON(github.event.commits) }}' | jq -r ".[].id" |
+             xargs -r -i git log -1 --pretty='%H%x09%s%x09%ce%x09-%(trailers:key=Signed-off-by,valueonly,separator=%x00)' '{}' |
+             tee /tmp/commits |
+             cut -f1,2
+          echo ''
+          if grep -e '-$' /tmp/commits | cut -f1,2 | grep -e '^' > /tmp/bad-commits; then
+             echo 'Сommits that fail verification:'
+             cat /tmp/bad-commits
+             echo ''
+             echo 'The DCO Signoff Check for all commits has FAILED.'
+             echo 'See https://github.com/legionus/libshell/blob/master/CONTRIBUTING.md'
+             echo ''
+             exit 1
+          fi
+
   check-dash:
     runs-on: ubuntu-latest
     needs: [ lint-shell ]
